### ISSUE TITLE
Sqlx-core v0.7.2 doesn't compile with Rust nightly version 1.75.0

### ISSUE THREAD

**Issue by mario-nt** [torrust/torrust-index#371]
The project cannot be built with the latest nightly versions of Rust (Nightly version 1.75.0) as sqlx-core cannot be built.

This affects building the project locally and the CI workflow with Docker.

When executing cargo build the following errors are shown:

```bash
cargo build
   Compiling sqlx-core v0.7.2
   Compiling unicode-script v0.5.5
   Compiling matches v0.1.10
   Compiling roxmltree v0.14.1
   Compiling heck v0.4.1
   Compiling svgtypes v0.8.2
   Compiling kurbo v0.8.3
   Compiling walkdir v2.4.0
   Compiling data-url v0.1.1
   Compiling rustls v0.21.8
   Compiling unic-char-property v0.9.0
   Compiling unic-ucd-version v0.9.0
   Compiling rustybuzz v0.4.0
   Compiling num-bigint v0.4.4
   Compiling fontdb v0.7.0
   Compiling globset v0.4.13
   Compiling stacker v0.1.15
   Compiling hyper v0.14.27
   Compiling png v0.17.10
error[E0308]: mismatched types
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/any/database.rs:32:21
    |
32  |     type Database = Any;
    |                     ^^^ lifetime mismatch
    |
    = note: expected associated type `<any::database::Any as HasValueRef<'r>>::Database`
               found associated type `<any::database::Any as HasValueRef<'r>>::Database`
note: the required lifetime does not necessarily outlive the lifetime `'r` as defined here
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/any/database.rs:31:6
    |
31  | impl<'r> HasValueRef<'r> for Any {
    |      ^^
note: the lifetime requirement is introduced here
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/database.rs:119:20
    |
119 |     type Database: Database;
    |                    ^^^^^^^^

error[E0308]: mismatched types
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/any/database.rs:32:21
    |
32  |     type Database = Any;
    |                     ^^^ lifetime mismatch
    |
    = note: expected associated type `<any::database::Any as HasValueRef<'r>>::Database`
               found associated type `<any::database::Any as HasValueRef<'r>>::Database`
note: the lifetime `'r` as defined here doesn't meet the lifetime requirements
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/any/database.rs:31:6
    |
31  | impl<'r> HasValueRef<'r> for Any {
    |      ^^
note: the lifetime requirement is introduced here
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/database.rs:119:20
    |
119 |     type Database: Database;
    |                    ^^^^^^^^

error[E0308]: mismatched types
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/any/database.rs:38:21
    |
38  |     type Database = Any;
    |                     ^^^ lifetime mismatch
    |
    = note: expected associated type `<any::database::Any as HasStatement<'q>>::Database`
               found associated type `<any::database::Any as HasStatement<'q>>::Database`
note: the required lifetime does not necessarily outlive the lifetime `'q` as defined here
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/any/database.rs:37:6
    |
37  | impl<'q> HasStatement<'q> for Any {
    |      ^^
note: the lifetime requirement is introduced here
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/database.rs:153:20
    |
153 |     type Database: Database;
    |                    ^^^^^^^^

error[E0308]: mismatched types
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/any/database.rs:38:21
    |
38  |     type Database = Any;
    |                     ^^^ lifetime mismatch
    |
    = note: expected associated type `<any::database::Any as HasStatement<'q>>::Database`
               found associated type `<any::database::Any as HasStatement<'q>>::Database`
note: the lifetime `'q` as defined here doesn't meet the lifetime requirements
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/any/database.rs:37:6
    |
37  | impl<'q> HasStatement<'q> for Any {
    |      ^^
note: the lifetime requirement is introduced here
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/database.rs:153:20
    |
153 |     type Database: Database;
    |                    ^^^^^^^^

error[E0308]: mismatched types
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/any/database.rs:44:21
    |
44  |     type Database = Any;
    |                     ^^^ lifetime mismatch
    |
    = note: expected associated type `<any::database::Any as HasArguments<'q>>::Database`
               found associated type `<any::database::Any as HasArguments<'q>>::Database`
note: the required lifetime does not necessarily outlive the lifetime `'q` as defined here
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/any/database.rs:43:6
    |
43  | impl<'q> HasArguments<'q> for Any {
    |      ^^
note: the lifetime requirement is introduced here
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/database.rs:135:20
    |
135 |     type Database: Database;
    |                    ^^^^^^^^

error[E0308]: mismatched types
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/any/database.rs:44:21
    |
44  |     type Database = Any;
    |                     ^^^ lifetime mismatch
    |
    = note: expected associated type `<any::database::Any as HasArguments<'q>>::Database`
               found associated type `<any::database::Any as HasArguments<'q>>::Database`
note: the lifetime `'q` as defined here doesn't meet the lifetime requirements
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/any/database.rs:43:6
    |
43  | impl<'q> HasArguments<'q> for Any {
    |      ^^
note: the lifetime requirement is introduced here
   --> /home/mario/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sqlx-core-0.7.2/src/database.rs:135:20
    |
135 |     type Database: Database;
    |                    ^^^^^^^^

   Compiling pest_derive v2.7.5
   Compiling mime_guess v2.0.4
For more information about this error, try `rustc --explain E0308`.
error: could not compile `sqlx-core` (lib) due to 6 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `sqlx-core` (lib) due to 6 previous errors

```

The stable version of Rust 1.73.0 compiles the project and runs it with no errors.

**Comment by mario-nt** [comment]
@josecelano @da2ce7

**Comment by josecelano** [comment]
There are two open issues:

- https://github.com/launchbadge/sqlx/issues/2855
- https://github.com/rust-lang/rust/issues/117598

**Comment by da2ce7** [comment]
- #https://github.com/rust-lang/rust/issues/117598

Has assigned it as a high priority issue, it should be fixed quire quickly.  I suggest that we just wait.

**Comment by josecelano** [comment]
Closed via https://github.com/rust-lang/rust/issues/117598
